$('.owl-carousel').owlCarousel({
  loop:true,
  margin:25,
  nav:false,
  autoplay:true,
  autoplayTimeout: 3000,
  dotsEach:true,
  pullDrag:true,
  responsive:{
      0:{
          items:1
      },
      600:{
          items:2
      },
      1000:{
          items:2
      }
  }
})